apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
  labels:
    app: kune-scan1 
  name: kube-scan1
  namespace: kube-bench
spec:
  replicas: 1
  revisionHistoryLimit: 10
  nodeSelector:
    node-role.kubernetes.io/compute: "true"
  selector:
    app: kube-scan1 
    deploymentconfig: kube-scan1
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: kube-scan1 
        deploymentconfig: kube-scan1 
    spec:
      containers:
      - image: docker-registry.default.svc:5000/default/kscan-new3
        imagePullPolicy: IfNotPresent
        name: kube-scan1 
        ports:
        - containerPort: 10000 
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: kube-storage
            mountPath: /tmp/kuberesults
            readOnly: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: golang-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: kube-storage
          persistentVolumeClaim:
            claimName: kube-pvc

