apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: kube-scan1 
    name: kube-scan1 
    namespace: kube-bench
  spec:
    ports:
    - name: 10000-tcp
      port: 10000 
      protocol: TCP
      targetPort: 10000 
    selector:
      app: kube-scan1
      deploymentconfig: kube-scan1
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List

