apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: 2021-01-10T13:57:31Z
  finalizers:
  - kubernetes.io/pv-protection
  name: pv0002
  resourceVersion: "28103"
  selfLink: /api/v1/persistentvolumes/pv0002
  uid: c8847eaa-534b-11eb-9fbd-000c2943ac76
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: kube-pvc
    namespace: kube-bench
    resourceVersion: "28101"
    uid: cab85840-534b-11eb-9fbd-000c2943ac76
  nfs:
    path: /volume1/SHARED/registry
    server: 192.168.0.210
  persistentVolumeReclaimPolicy: Retain
status:
  phase: Bound
